window.productList = [
    {
      category: "Monitor",
      items: [
        { name: "YK-700HD", subCategory: "5,6,7 Inch", description: "-", image: "images/product/700HD.jpeg", pdf:"pdfs/monitor/YK-700HD.pdf",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", "7 inch Digital (Diagonal)"],
            ["Number of Pixels","800 X 3(RGB) X 480"],
            ["Active area","154.08. X 86.58 mm"],
            ["Luminance","400㏅/㎡"],
            ["Input","AV1 (Analog HD/ TVI/ CVBS<br>AV2 (Analog HD/ TVI/ CVBS"],
            ["Key Button","5 Key (Menu/Left/Right/Sel/AV&PWR)"],
            ["Video System","NTSC<br>720@30fps<br>1080p@30fps"],
            ["Audio Output", "(Option)"],
            ["Power Source","DC12V ~ 24V"],
            ["Power Consumption", "10W"],
            ["Operation Temperature", "-20℃ ~ 60℃"],
            ["Storage Temperature", "-30℃ ~ 80℃"],
            ["Weight", "About 350g"],
            ["Dimension", "184(W) X 109(H) x 16.5(D)"],
            ["Other", "RearView System"],
            ["Accessory", "Remote Control<br>Sub_Cable(1.5M)_DIN Connector"],
          ] },
          { name: "YK-7WML", subCategory: "5,6,7 Inch",description: "-", image: "images/product/7WML.jpeg", pdf:"pdfs/monitor/YK-7WML.pdf",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", "7 Inch Digital (Diagonal)"],
            ["Number of Pixels","800 X 3(RGB) X 480"],
            ["Active area","154.08mm x 86.58mm"],
            ["Luminance","400 cd/m²"],
            ["Input","AV1 (CVBS + Audio_Mono)<br>RearView System<br>AV2(CVBS)(Audio Option)"],
            ["Key Button","5 Key (Menu/Left/Right/Sel/AV&PWR)"],
            ["Color System", "NTSC or PAL"],
            ["Audio Output", "Built in Speaker(Mono)"],
            ["Power Source","DC 12V ~24V"],
            ["Power Consumption", "6W"],
            ["Operation Temperature", "-20℃ ~ 60℃"],
            ["Storage Temperature", "-30℃ ~ 80℃"],
            ["Weight", "350g"],
            ["Dimension", "184(W) X 109(H) x 16.5(D)"],
            ["Other", ""],
            ["Accessory", "Remote Control,<br>Sub Cable (1.5M)"],
          ] }, 
          { name: "YK-730HD", subCategory:"5,6,7 Inch",description: "-", image: "images/product/730HD.jpeg", pdf:"pdfs/monitor/YK-730HD.pdf",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Display Size", "7 Inch Digital (Diagonal)"],
          ["Number of Pixels","800 X 3 (RGB) X 480"],
          ["Input","AHD1<br>AHD2"],
          ["Video System","AHD 720p@30fps<br>AHD1080p@30fps<br>NTSC"],
          ["Power Source","DC 12-24V"],
          ["Power Consumption","7W (Under)"],
          ["Operation Temperature","-20℃ ~ 60℃"],
          ["Storage Temperature", "-30℃ ~ 80℃"],
          ["Weight","290g"],
          ["Dimension", "182(W) X 120(H) X 24(D)"],
          ["Accessory", "Sub Cable(1.5M)_DIN Connector"],
        ] },
        { name: "YK-730M", subCategory:"5,6,7 Inch", description: "-", image: "images/product/730M.jpeg", pdf:"pdfs/monitor/YK-730M.pdf",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Display Size", "7 Inch Digital (Diagonal)"],
          ["Number of Pixels","800 X 3 (RGB) X 480"],
          ["Input","Video1(CVBS)<br>Video2(CVBS)"],
          ["Color System","NTSC"],
          ["Power Source","DC 12-24V"],
          ["Power Consumption","5W (Under)"],
          ["Operation Temperature","-20℃ ~ 60℃"],
          ["Storage Temperature", "-30℃ ~ 80℃"],
          ["Weight","280g"],
          ["Dimension", "182(W) X 120(H) X 24(D)"],
          ["Accessory", "Sub Cable(1.5M)_DIN Connector"],
        ] },
        { name: "YK-W700HD (IPS)", subCategory:"5,6,7 Inch", description: "-", image: "images/product/W700HD_IPS.jpeg", pdf:"pdfs/monitor/YK-W700HD(IPS).pdf",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Display Size", "7 Inch Digital (Diagonal)<br>IPS panel"],
          ["Number of Pixels","1024 X 3 (RGB X 600"],
          ["Luminance","700 ㏅/㎡"],
          ["Input","CAM1(AnalogHD/TVI)-audio option<br>CAM2(AnalogHD/TVI)"],
          ["Key Button","6 Key (Menu/ Left/ Right/ Sel/ AV/ PWR)<br>Capacitive touch button"],
          ["Water Resistant","IP69K"],
          ["Audio Output", ""],
          ["Power Source","10W"],
          ["Operation Temperature","-20℃ ~ 60℃"],
          ["Storage Temperature", "-30℃ ~ 80℃"],
          ["Weight", "820g"],
          ["Dimension", "191(W) X 135(H) X 35(D)mm"],
          ["Case", "Metal die-casting housing"],
          ["Function", "*IPS panel Viewing Angle<br>(up/down/left/right 80°<br><br>*Maximum Video Trigger Linkage<br>*AUTO DIMMER<br>*Parking assistance system"],
          ["Accessory", "Remote Control-option"],
        ] },
        { name: "YK-101HM", subCategory: "8,9,10 Inch", description: "-", image: "images/product/101HM.jpeg", pdf:"pdfs/monitor/YK-101HM.pdf",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Display Size", "10.1Inch (Diagonal)-IPS Panel"],
          ["Number of Pixels","1024 X 3(RGB) X600"],
          ["Luminance","550 ㏅/㎡"],
          ["Input","AV/CVBS + Audio L/R:RCA<br>HDMI/ up to 1080p: HDMI + A type<br>PC/ Up to 1080p: 15pin D-SUB<br>USB/Picture/Music/Movie:USB+A Type"],
          ["Output", "Built in Speaker-Stereo<br>Earphone out"],
          ["Key Button","7 Key"],
          ["Power Source","DC12-24V"],
          ["Power Consumption","8W"],
          ["Operation Temperature", "-20℃ ~ 60℃"],
          ["Storage Temperature", "-30℃ ~ 80℃"],
          ["Weight", "500g"],
          ["Dimension", "260(W) X 160(H) X 30.5(D)mm"],
          ["Other", "Built in Speaker"],
          ["Accessory", "Remote Control"],
        ] },
        { name: "YK-900HD (IPS)", subCategory:"8,9,10 Inch",description: "-", image: "images/product/900HD_IPS.jpeg", pdf:"pdfs/monitor/YK-900HD.pdf",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Display Size", "9Inch Digital (Diagonal)"],
          ["Number of Pixels","1024 X 3(RGB) X 600"],
          ["Luminance","400 ㏅/㎡"],
          ["Input","AV1 (AnalogHD/TVI/CVBS)<br>AV2 (AnalogHD/TVI/CVBS)<br>HDMI (720p/1080p)"],
          ["Key Button","5 Key(Menu/Left/Right/Sel/AV&PWR)"],
          ["Video System","NTSC /PAL /720p@30fps / 1080p@30fps"],
          ["Audio Output", "Built in Speaker (Mono)"],
          ["Power Source","DC 12-24V"],
          ["Power Consumption","10W"],
          ["Operation Temperature", "-20℃ ~ 60℃"],
          ["Storage Temperature", "-30℃ ~ 80℃"],
          ["Weight", "470g"],
          ["Dimension", "230(W) X 138(H) X 19.5(D)mm"],
          ["Accessory", "Remote Control<br>CABLE 1.5M"],
          ["Other", ""],
        ] },
        { name: "YK-5WML", subCategory:"5,6,7 Inch", description: "-", image: "images/product/YK-5WML.png", pdf: "pdfs/monitor/YK-5WML.pdf",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", "5 Inch NORMAL (4:3)"],
            ["Number of Pixels","320 x 324"],
            ["Back Light","CCFL Type"],
            ["Luminance","300cd/㎡"],
            ["Video Input","V1,V2: 1Vp-p(CVBS 75ohm)"],
            ["Audio Output", "None"],
            ["View Angle","10*30*45*45 : UP*.DOWN*.L*.R"],
            ["System","NTSC"],
            ["Video Jack","RCA CABLE"],
            ["Dc input","DC 12V ~ 24V"],
            ["Dc current","0.8A"],
            ["Operation Temperature", "-20℃ ~ 60℃"],
            ["Storage Temperature", "-30℃ ~ 80℃"],
            ["Weight", "350g"],
            ["Dimension", "142 X 99 X 25.5mm"],
          ] },
          { name: "YK-830M", subCategory:"8,9,10 Inch",description: "-", image: "images/product/YK-830M.png", pdf:"pdfs/monitor/YK-830M.pdf",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", "8 Inch LCD (Diagonal)<br>(CCFL BACK LIGHT LCD)"],
            ["Number of Pixels","800 X 3(RGB) X 600"],
            ["Input","Video1 (CVBS)<br>Video2(CVBS)"],
            ["Video System","NTSC"],
            ["Power Consumption", "Less than 12W"],
            ["Power Source","DC 12 -24V"],
            ["Operation Temperature", "-20℃ ~ 60℃"],
            ["Storage Temperature", "-30℃ ~ 80℃"],
            ["Weight", "620g"],
            ["Dimension", "234(W) X 158(H) x 33(D)mm"],
            ["Accessory", "Remote Control<br>Sub Cable(1.5M)_DIN Connector"],
          ] },
          { name: "YK-101QM", subCategory:"8,9,10 Inch",description: "-", image: "images/product/YK-101QM.png", pdf: "pdfs/monitor/YK-101QM.pdf",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", "10.1 Inch (Diagonal)<br>IPS Panel"],
            ["Number of Pixels","1024 X 3(RGB) X 600"],
            ["Active area",""],
            ["Luminance","550 ㏅/㎡"],
            ["Video Input","AHD x 4 CH<br>RCA X 4"],
            ["Camera Format","720p@25fps"],
            ["Support","720@30fps<br>1080p@25fps,<br>1080p@30fps"],
            ["Key Button","6 Key"],
            ["Video System",""],
            ["Power Consumption", "6W"],
            ["Power Source","DC 12-24V"],
            ["Operation Temperature", "-20℃ ~ 60℃"],
            ["Storage Temperature", "-30℃ ~ 80℃"],
            ["Weight", "600g"],
            ["Dimension", "260(W) X 160(H) X 30.5(D)mm"],
            ["Other", "Built in Speaker"],
            ["Accessory", "Remote Control<br>EXT. CABLE : (Length = 1.5M) - Total = 2 Meter"],
          ] },
          { name: "YK-900HD", subCategory:"8,9,10 Inch",description: "-", image: "images/product/900HD_IPS.jpeg", pdf: "pdfs/monitor/",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", "10.1 Inch (Diagonal)<br>IPS Panel"],
            ["Number of Pixels","1024 X 3(RGB) X 600"],
            ["Active area",""],
            ["Luminance","550 ㏅/㎡"],
            ["Video Input","AHD x 4 CH<br>RCA X 4"],
            ["Camera Format","720p@25fps"],
            ["Support","720@30fps<br>1080p@25fps,<br>1080p@30fps"],
            ["Key Button","6 Key"],
            ["Video System",""],
            ["Power Consumption", "6W"],
            ["Power Source","DC 12-24V"],
            ["Operation Temperature", "-20℃ ~ 60℃"],
            ["Storage Temperature", "-30℃ ~ 80℃"],
            ["Weight", "600g"],
            ["Dimension", "260(W) X 160(H) X 30.5(D)mm"],
            ["Other", "Built in Speaker"],
            ["Accessory", "Remote Control<br>EXT. CABLE : (Length = 1.5M) - Total = 2 Meter"],
          ] },
          { name: "YK-1030HD", subCategory:"8,9,10 Inch",description: "-", image: "images/product/tbu.jpeg", pdf: "pdfs/monitor/",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", "10.1 Inch (Diagonal)<br>IPS Panel"],
            ["Number of Pixels","1024 X 3(RGB) X 600"],
            ["Active area",""],
            ["Luminance","550 ㏅/㎡"],
            ["Video Input","AHD x 4 CH<br>RCA X 4"],
            ["Camera Format","720p@25fps"],
            ["Support","720@30fps<br>1080p@25fps,<br>1080p@30fps"],
            ["Key Button","6 Key"],
            ["Video System",""],
            ["Power Consumption", "6W"],
            ["Power Source","DC 12-24V"],
            ["Operation Temperature", "-20℃ ~ 60℃"],
            ["Storage Temperature", "-30℃ ~ 80℃"],
            ["Weight", "600g"],
            ["Dimension", "260(W) X 160(H) X 30.5(D)mm"],
            ["Other", "Built in Speaker"],
            ["Accessory", "Remote Control<br>EXT. CABLE : (Length = 1.5M) - Total = 2 Meter"],
          ] },
          { name: "LV-609MM", subCategory: "Others", description: "-", image: "images/product/LV-609MM.png", pdf: "pdfs/monitor/LV-609MM.pdf",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", "6 Inch(Digital)"],
            ["Number of Pixels","800 X 3(RGB) X 480"],
            ["Active area","133mm X 73mm"],
            ["Luminance","400㏅/㎡"],
            ["System", "NTSC or PAL"],
            ["Input","V1, V2, V3 (CVBS)"],
            ["Power Source","DC 12V ~ 24V"],
            ["Operation Temperature", "0℃ ~ 60℃"],
            ["Storage Temperature", "-10℃ ~ 70℃"],
            ["Weight", "400g"],
            ["Dimension", "304(W) X 96(H) X 15 (D)mm"],
            ["Other", "Remote Control<br>RearView System<br>Driving System-option<br>AUdio(Mono)-option"],
            ["Accessory", "4M cable"],
          ] },

          /*{ name: "To Be Updated", subCategory:"",description: "-", image: "images/comingsoon.jpeg",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", ""],
            ["Number of Pixels",""],
            ["Active area",""],
            ["Luminance",""],
            ["Input",""],
            ["Key Button",""],
            ["Video System",""],
            ["Audio Output", ""],
            ["Power Source",""],
            ["Operation Temperature", ""],
            ["Storage Temperature", ""],
            ["Weight", ""],
            ["Dimension", ""],
            ["Other", ""],
            ["Accessory", ""],
          ] },
          { name: "To Be Updated", subCategory:"",description: "-", image: "images/comingsoon.jpeg",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", ""],
            ["Number of Pixels",""],
            ["Active area",""],
            ["Luminance",""],
            ["Input",""],
            ["Key Button",""],
            ["Video System",""],
            ["Audio Output", ""],
            ["Power Source",""],
            ["Operation Temperature", ""],
            ["Storage Temperature", ""],
            ["Weight", ""],
            ["Dimension", ""],
            ["Other", ""],
            ["Accessory", ""],
          ] },*/
      ]
      
    },
    {
      category: "Camera",
      items: [
        { name: "YK-230HIR", description: "-", image: "images/product/230HIR.jpeg", pdf: "pdfs/cam/YK-230HIR.pdf",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Image Sensor", "1/3/inch SONY Super Sensitivity Color Sensor "],
          ["S/N Ratio",">50dB"],
          ["Resolution","960(H) X 480 (V)"],
          ["Video Out","NTSC"],
          ["Lense","Board Lens 2.5mm Fixed Iris"],
          ["Angle of View","D/H/V: 134°/115°/68°"],
          ["Operating Voltage","DC 12V-40V"],
          ["Consumption", "60mA, 120mA(IR)"],
          ["Weight", "113g"],
          ["Dimension", "≈53(W) X 40(H) X 50(D)"],
          ["Other", "IR(Infrared Radiation)*4"],
          ["Water Resistance", "IP69"],
        ] },
        { name: "YKC-400HD", description: "-", image: "images/product/YKC-400HD.png", pdf:"pdfs/cam/YKC-400HD.pdf",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Image Sensor", "1/3 Inch Sony CMOS Image sensor"],
          ["Resolution","1280(H) X 720(V)"],
          ["Video Out","AHD 720P/30fps"],
          ["Lense","Wide view lens (Diagonal 210°)"],
          ["Angle of View","Max horizontal field of view 170°<br>Max vertical field of view 130°"],
          ["Operating Voltage","DC 10V ~ 32V<br>(Maximum surge voltrage 40V)"],
          ["Consumption", "Approx. 1.5W (When IR is inactive)"],
          ["Operating Temperature","-20℃ ~ 70℃"],
          ["Weight", "Approx. 140g (w/o cable)"],
          ["Dimension", "76 (W) X 50(H) X 44(D)"],
          ["Other", "Infrared lamp X 8<br>IP69K<br>E-Mark Certified"],
          ["Accessory", "Mounting Bracket<br>Screw kit"],
        ] },
        { name: "YKC-20A", description: "-", image: "images/product/YKC-20A.png", pdf:"pdfs/cam/YKC-20A.pdf",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Image Sensor", "1/3 Inch CMOS Image sensor"],
          ["S/N Ratio","44dB (Max)"],
          ["Signal System","NTSC or PAL"],
          ["Resolution","720(H) X 480(V)"],
          ["Video Out","Composite (1Vp-p, 75 ohm)"],
          ["Lense","Wide view lens (Diagonal 210°)"],
          ["Angle of View","Horizontal Field of View: 140° ~ 150°<br>Vertical Field of View:110° ~ 120°"],
          ["Operating Voltage","DC 10V ~ 32V (MAX 40V)"],
          ["Consumption", "Approx. 1.5 W"],
          ["Operating Temp","-20℃ ~ 70℃"],
          ["Weight", "75g (w/o cables)"],
          ["Dimension", "32 (W) X 30(H) X 38(D)"],
          ["Accessory", "Mounting Bracket<br>Screw kit"],
        ] },
        { name: "YKC-200HD", description: "-", image: "images/product/YKC-200HD.png", pdf:"pdfs/cam/YKC-200HD",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Image Sensor", "1/3 Inch Sony CMOS Image sensor"],
          ["S/N Ratio",""],
          ["Resolution","1280(H) X 720(V)"],
          ["Video Out","AHD 720P/30fps"],
          ["Audio","In-built mic (-40 ±3dB)"],
          ["Lense","Wide view lens (Diagonal 210°)"],
          ["Angle of View","Horizontal Field of View > 160°<br>Vertical Field of View > 120°"],
          ["Operating Voltage","DC 10V ~ 32V<br>(Maximum Surge Voltage 40V)"],
          ["Consumption", "Approx. 1.5W (when IR is inactive)"],
          ["Operating Temp","-20℃ ~ 70℃"],
          ["Weight", "Approx. 190g (w/o cable)"],
          ["Dimension", "Approx. 76 (W) X 47(H) X 42(D)"],
          ["Other", "Infrared lamp X 8<br>IP69K<br>E-mark Certified"],
          ["Accessory", "Mounting Bracket<br>Screw kit"],
        ] },
        { name: "YK-21SL", description: "-", image: "images/product/YK_21SL.png", pdf: "pdfs/cam/YK-21SL(EN).pdf",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Image Sensor", "1/2.8″ SONY(STARVIS) CMOS "],
          ["Resolution","1920x1080p (30fps)"],
          ["Lense","2.8mm 3Mega Pixel lens"],
          ["DAY & NIGHT","STARLIGHT 0 , 1 , 2"],
          ["Min. illumination","More than 0.01 lux"],
          ["DNR (3D + 2D", "Off /Low /Middle /High"],
          ["White Balance", "ATW"],
          ["Language", "ENG"],
          ["Power Input", "DC12V - DC24V"],
          ["Temperature", "- 10°C ~ +50°C"],
          ["Power Consumption", "Normal: 120mA"],
          ["Dimension", "53.5(W) x 58 (D) x 40.5 (H) mm"],
        ] },
        /*{ name: "YKC-400HD", description: "-", image: "images/comingsoon.jpeg",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Image Sensor", ""],
          ["S/N Ratio",""],
          ["Resolution",""],
          ["Video Out",""],
          ["Lense",""],
          ["Angle of View",""],
          ["Operating Voltage",""],
          ["Consumption", ""],
          ["Weight", ""],
          ["Dimension", ""],
          ["Other", ""],
          ["Accessory", ""],
        ] },*/

      ]
    },
    {
      category: "Wireless TX/RX",
      items: [
        { name: "YK-700RXM (RX Monitor)", description: "-", image: "images/product/YK-700RXM.png", pdf:"pdfs/wireless/YK-700RXM(RX MONITOR).pdf",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", "7 Inch (Diagonal)"],
            ["Resolution","800 X 480"],
            ["Luminance","400 ㏅/㎡"],
            ["External Input","AV1 (CVBS + MONO)"],
            ["Frequency","2400~2483 Mhz"],
            ["Receive","VIDEO/AUDIO"],
            ["Audio Output", "Built in Speaker"],
            ["Modulation","BPSK/QPSK/16QAM"],
            ["Operating Voltage","DC10V~32V"],
            ["Power Consumption","≈7W"],
            ["Operation Temperature", "0°∼60°"],
            ["Weight", "370g"],
            ["Dimension", "184(W) X 109(H) X 16.5(D)"],
            ["Other", "FM-TX (88.3~90.0 Mhz)"],
            ["Accessory", "Cable (Option)<br>Remote Control"],
          ] },
          { name: "YKC-300HD (TX Camera)", description: "-", image: "images/product/YKC-300HD(TX camera).png", pdf: "pdfs/wireless/YKC-300HD(TX CAMERA).pdf",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Image Sensor", "1/3inch CMOS Image Sensor"],
            ["Resolution","1280(H) X 720(V)"],
            ["Video Out","AHD 720P/30fps"],
            ["LENS","Wide view lens (Diagonal 210°)"],
            ["Angle of View","Max Horizontal Field of View 170°<br>Max Vertical Field Of View 130°"],
            ["Composite Video Output ","1Vp-p, 75ohm"],
            ["Reliable Reception Range ",">>80m"],
            ["Frequency","2400~2483 Mhz"],
            ["Modulation","OFDM/CCK"],
            ["Operating Voltage","DC 10V ~ 24V"],
            ["Power Consumption","320mA,12V/160mA,24V(When IR is inactive)"],
            ["Operation Temperature", "-30°∼70°"],
            ["Weight", "≈160g (w/o cable)"],
            ["Dimension", "76 (W) X 50(H) X 44(D)"],
            ["Other", "IR lamp X 8 <br>IP69K)"],
            ["Accessory", ">Mounting Bracket<br>Screw Kit"],
          ] },
      ]
    },
    {
      category: "ADAS and others",
      items: [

          { name: "ChildGuard Alarm", subCategory:"",description: "", image: "images/product/YK-S02_i1.png", pdf: "pdfs/ADAS/YK-S02.pdf",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Main Unit","-"],
            ["Operating Voltage", "DC 12V ~24V"],
            ["Max. Power Consumption",""],
            ["Stand by Mode","Approx. 25mA (12V)<br>Approx. 15mA (24V)"],
            ["Safety Confirmation Mode","Approx. 120mA (12V)<br>Approx. 60mA (24V)"],
            ["Operating Temperature","-30°∼85°"],
            ["Weight","138g (w/o cable)"],
            ["Dimensions","114 x 88 x 30.5mm"],
            ["Dust/Waterproof Rating", "IP40"],
            ["Alarm","-"],
            ["dB Level", "110±3 dB"],
            ["Max. power Consumption", "Approx. 800mA (12V)<br>Approx. 550mA (24V)"],
            ["Weight", "190g (w/o cable)"],
            ["Dimension", "56(68) x 73 x 74 mm"],
            ["Dust/Waterproof Rating", "IP54"],
          ] },

          { name: "Ultrasonic Object Sensor", subCategory:"",description: "", image: "images/product/YK-S01_1.png", pdf: "pdfs/ADAS/YK-S01.pdf",
          specs:[
            ["", ""],

          ] },
                   
          { name: "To Be Updated", subCategory:"",description: "-", image: "images/product/tbu.jpeg",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", ""],
            ["Number of Pixels",""],
            ["Active area",""],
            ["Luminance",""],
            ["Input",""],
            ["Key Button",""],
            ["Video System",""],
            ["Audio Output", ""],
            ["Power Source",""],
            ["Operation Temperature", ""],
            ["Storage Temperature", ""],
            ["Weight", ""],
            ["Dimension", ""],
            ["Other", ""],
            ["Accessory", ""],
          ] },
          
      ]
    },
    
    /*{
      category: "Assistance System",
      items: [
        { name: "To Be Updated", description: "-", image: "images/comingsoon.jpeg",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", ""],
            ["Number of Pixels",""],
            ["Active area",""],
            ["Luminance",""],
            ["Input",""],
            ["Key Button",""],
            ["Video System",""],
            ["Audio Output", ""],
            ["Power Source",""],
            ["Operation Temperature", ""],
            ["Storage Temperature", ""],
            ["Weight", ""],
            ["Dimension", ""],
            ["Other", ""],
            ["Accessory", ""],
          ] },
          
      ]
    }*/
  ];

 