window.productList = [
    {
      category: "Monitor",
      items: [
        { name: "YK-700HD", description: "-", image: "images/700HD.jpeg",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", "7 inch Digital (Diagonal)"],
            ["Number of Pixels","800 X 3(RGB) X 480"],
            ["Active area","154.08. X 86.58 mm"],
            ["Luminance","400㏅/㎡"],
            ["Input","AV1 (Analog HD/ TVI/ CVBS<br>AV2 (Analog HD/ TVI/ CVBS"],
            ["Key Button","5 Key (Menu/Left/Right/Sel/AV&PWR)"],
            ["Video System","NTSC<br>720@30fps<br>1080p@30fps"],
            ["Audio Output", "(Option)"],
            ["Power Source","DC12V ~ 24V"],
            ["Operation Temperature", "10W"],
            ["Storage Temperature", "-20℃ ~ 70℃"],
            ["Weight", "About 350g"],
            ["Dimension", "184(W) X 109(H) x 16.5(D)"],
            ["Other", "RearView System"],
            ["Accessory", "Remote Control<br>Sub_Cable(1.5M)_DIN Connector"],
          ] },
          { name: "YK-7WML", description: "-", image: "images/7WML.jpeg",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", "7 Inch Digital (Diagonal)"],
            ["Number of Pixels","800 X 3(RGB) X 480"],
            ["Active area","154.08mm x 86.58mm"],
            ["Luminance","400 cd/m²"],
            ["Input","AV1 (CVBS + Audio_Mono)<br>RearView System<br>AV2(CVBS)(Audio Option)"],
            ["Key Button","5 Key (Menu/Left/Right/Sel/AV&PWR)"],
            ["Color System", "NTSC or PAL"],
            ["Audio Output", "Built in Speaker(Mono)"],
            ["Power Source","DC 12V ~24V"],
            ["Power Consumption", "6W"],
            ["Operation Temperature", "0℃ ~ 60℃"],
            ["Storage Temperature", "-10℃ ~ 70℃"],
            ["Weight", "350g"],
            ["Dimension", "184(W) X 109(H) x 16.5(D)"],
            ["Other", ""],
            ["Accessory", "Remote Control,<br>Sub Cable (1.5M)"],
          ] }, 
          { name: "YK-730HD", description: "-", image: "images/730HD.jpeg",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Display Size", "7 Inch Digital (Diagonal)"],
          ["Number of Pixels","800 X 3 (RGB) X 480"],
          ["Input","AHD1<br>AHD2"],
          ["Video System","AHD 720p@30fps<br>AHD1080p@30fps<br>NTSC"],
          ["Power Source","DC 12-24V"],
          ["Power Consumption","7W (Under)"],
          ["Operation Temperature","-20℃ ~ 60℃"],
          ["Storage Temperature", "-30℃ ~ 70℃"],
          ["Weight","290g"],
          ["Dimension", "182(W) X 120(H) X 24(D)"],
          ["Accessory", "Sub Cable(1.5M)_DIN Connector"],
        ] },
        { name: "YK-730M", description: "-", image: "images/730M.jpeg",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Display Size", "7 Inch Digital (Diagonal)"],
          ["Number of Pixels","800 X 3 (RGB) X 480"],
          ["Input","Video1(CVBS)<br>Video2(CVBS)"],
          ["Color System","NTSC"],
          ["Power Source","DC 12-24V"],
          ["Power Consumption","5W (Under)"],
          ["Operation Temperature","-20℃ ~ 60℃"],
          ["Storage Temperature", "-30℃ ~ 70℃"],
          ["Weight","280g"],
          ["Dimension", "182(W) X 120(H) X 24(D)"],
          ["Accessory", "Sub Cable(1.5M)_DIN Connector"],
        ] },
        { name: "YK-W700HD (IPS)방수", description: "-", image: "images/W700HD_IPS.jpeg",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Display Size", "7 Inch Digital (Diagonal)<br>IPS panel"],
          ["Number of Pixels","1024 X 3 (RGB X 600"],
          ["Luminance","700 ㏅/㎡"],
          ["Input","CAM1(AnalogHD/TVI)-audio option<br>CAM2(AnalogHD/TVI)"],
          ["Key Button","6 Key (Menu/ Left/ Right/ Sel/ AV/ PWR)<br>정전식 터치버튼"],
          ["Water Resistant","IP69K"],
          ["Audio Output", ""],
          ["Power Source","10W"],
          ["Operation Temperature", "-30℃ ~ 60℃"],
          ["Weight", "820g"],
          ["Dimension", "191(W) X 135(H) X 35(D)mm"],
          ["Case", "Metal die-casting housing"],
          ["Function", "*IPS panel Viewing Angle<br>(up/down/left/right 80°<br><br>*Maximum Video Trigger Linkage<br>*AUTO DIMMER<br>*Parking assistance system"],
          ["Accessory", "Remote Control-option"],
        ] },
        { name: "YK-101HM", description: "-", image: "images/101HM.jpeg",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Display Size", "10.1Inch (Diagonal)-IPS Panel"],
          ["Number of Pixels","1024 X 3(RGB) X600"],
          ["Luminance","550 ㏅/㎡"],
          ["Input","AV/CVBS + Audio L/R:RCA<br>HDMI/ up to 1080p: HDMI + A type<br>PC/ Up to 1080p: 15pin D-SUB<br>USB/Picture/Music/Movie:USB+A Type"],
          ["Output", "Built in Speaker-Stereo<br>Earphone out"],
          ["Key Button","7 Key"],
          ["Power Source","DC12-24V"],
          ["Power Consumption","8W"],
          ["Operation Temperature", "-20℃ ~ 60℃"],
          ["Storage Temperature", "-30℃ ~ 70℃"],
          ["Weight", "500g"],
          ["Dimension", "260(W) X 160(H) X 30.5(D)mm"],
          ["Other", "Built in Speaker"],
          ["Accessory", "Remote Control"],
        ] },
        { name: "YK-900HD (IPS)", description: "-", image: "images/900HD_IPS.jpeg",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Display Size", "9Inch Digital (Diagonal)"],
          ["Number of Pixels","1024 X 3(RGB) X 600"],
          ["Luminance","400 ㏅/㎡"],
          ["Input","AV1 (AnalogHD/TVI/CVBS)<br>AV2 (AnalogHD/TVI/CVBS)<br>HDMI (720p/1080p)"],
          ["Key Button","5 Key(Menu/Left/Right/Sel/AV&PWR)"],
          ["Video System","NTSC /PAL /720p@30fps / 1080p@30fps"],
          ["Audio Output", "Built in Speaker (Mono)"],
          ["Power Source","DC 12-24V"],
          ["Power Consumption","10W"],
          ["Operation Temperature", "-20℃ ~ 60℃"],
          ["Storage Temperature", "-30℃ ~ 70℃"],
          ["Weight", "470g"],
          ["Dimension", "230(W) X 138(H) X 19.5(D)mm"],
          ["Accessory", "Remote Control<br>CABLE 1.5M"],
          ["Other", ""],
        ] },

      ]
    },
    {
      category: "Camera",
      items: [
        { name: "YK-230HIR", description: "-", image: "images/230HIR.jpeg",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Image Sensor", "1/3/inch SONY Super Sensitivity Color Sensor "],
          ["S/N Ratio",">50dB"],
          ["Resolution","960(H) X 480 (V)"],
          ["Video Out","NTSC"],
          ["Lense","Board Lens 2.5mm Fixed Iris"],
          ["Angle of View","D/H/V: 134°/115°/68°"],
          ["Operating Voltage","DC 12V-40V"],
          ["Comsumption", "60mA, 120mA(IR)"],
          ["Weight", "113g"],
          ["Dimension", "≈53(W) X 40(H) X 50(D)"],
          ["Other", "IR(Infrared Radiation)*4"],
          ["Water Resistance", "IP69"],
        ] },
        { name: "BMC-21SL", description: "-", image: "images/BMC_21SL.png", pdf: "pdfs/BMC-21SL(EN).pdf",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Imagr Sensor", "1/2.8″ SONY(STARVIS) CMOS "],
          ["Resolution","1920x1080p (30fps)"],
          ["Lense","2.8mm 3Mega Pixel lens"],
          ["DAY & NIGHT","STARLIGHT 0 , 1 , 2"],
          ["Min. illumination","More than 0.01 lux"],
          ["DNR (3D + 2D", "Off /Low /Middle /High"],
          ["White Balance", "ATW"],
          ["Language", "ENG"],
          ["Power Input", "DC12V - DC24V"],
          ["Temperature", "- 10°C ~ +50°C"],
          ["Power Consumption", "Normal: 120mA"],
          ["Dimension", "53.5(W) x 58 (D) x 40.5 (H) mm"],
        ] },
        { name: "YKC-400HD", description: "-", image: "images/comingsoon.jpeg",
        specs:[
          ["ITEM", "DESCRIPTION"],
          ["Imagr Sensor", ""],
          ["S/N Ratio",""],
          ["Resolution",""],
          ["Video Out",""],
          ["Lense",""],
          ["Angle of View",""],
          ["Operating Voltage",""],
          ["Comsumption", ""],
          ["Weight", ""],
          ["Dimension", ""],
          ["Other", ""],
          ["Accessory", ""],
        ] },
      ]
    },
    {
      category: "Wireless",
      items: [
        { name: "YK-700RXM (RX Monitor)", description: "-", image: "images/700RXM.jpeg",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", "7 Inch (Diagonal)"],
            ["Resolution","800 X 480"],
            ["Luminance","400 ㏅/㎡"],
            ["External Input","AV1 (CVBS + MONO)"],
            ["Frequency","2400~2483 Mhz"],
            ["Receive","VIDEO/AUDIO"],
            ["Audio Output", "Built in Speaker"],
            ["Modulation","BPSK/QPSK/16QAM"],
            ["Operating Voltage","DC10V~32V"],
            ["Power Consumption","≈7W"],
            ["Operation Temperature", "0°∼60°"],
            ["Weight", "370g"],
            ["Dimension", "184(W) X 109(H) X 16.5(D)"],
            ["Other", "FM-TX (88.3~90.0 Mhz)"],
            ["Accessory", "Cable (Option)<br>Remote Control"],
          ] },
          { name: "YK-100TRX (TX Camera)", description: "-", image: "images/100TRX.jpeg",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Image Sensor", "1/3inch CMOS Image Sensor"],
            ["Signal System","NTSC"],
            ["Angle of View","Horizontal(140° ~ 150°)<br>Vertical (110° ~ 120°) "],
            ["Transmission","VIDEO/AUDIO"],
            ["Transmission Range",">>50Meter"],
            ["Frequency","2400~2483 Mhz"],
            ["Modulation","BPSK/QPSK/16QAM"],
            ["Operating Voltage","DC12V~24V"],
            ["Power Consumption","≈4W"],
            ["Operation Temperature", "-20°∼70°"],
            ["Weight", "≈250g"],
            ["Dimension", "76(W) X 47(H) X 42(D)"],
            ["Other", "IR*8)"],
            ["Accessory", "Cable (Option)<br>Mounting Bracket&Screw Kit"],
          ] },
      ]
    },
    {
      category: "Dash Cam, Advanced Room Mirror",
      items: [
        { name: "To Be Updated", description: "-", image: "images/comingsoon.jpeg",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", ""],
            ["Number of Pixels",""],
            ["Active area",""],
            ["Luminance",""],
            ["Input",""],
            ["Key Button",""],
            ["Video System",""],
            ["Audio Output", ""],
            ["Power Source",""],
            ["Operation Temperature", ""],
            ["Storage Temperature", ""],
            ["Weight", ""],
            ["Dimension", ""],
            ["Other", ""],
            ["Accessory", ""],
          ] },
      ]
    },
    {
      category: "Assistance System",
      items: [
        { name: "To Be Updated", description: "-", image: "images/comingsoon.jpeg",
          specs:[
            ["ITEM", "DESCRIPTION"],
            ["Display Size", ""],
            ["Number of Pixels",""],
            ["Active area",""],
            ["Luminance",""],
            ["Input",""],
            ["Key Button",""],
            ["Video System",""],
            ["Audio Output", ""],
            ["Power Source",""],
            ["Operation Temperature", ""],
            ["Storage Temperature", ""],
            ["Weight", ""],
            ["Dimension", ""],
            ["Other", ""],
            ["Accessory", ""],
          ] },
          
      ]
    }
  ];

 